---
driver:
  name: dokken
  chef_version: latest
  seccomp: unconfined
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - /var/run/docker.sock:/var/run/docker.sock
  cap_add:
  - SYS_ADMIN
  - NET_ADMIN
  tmpfs:
  - /run
  - /run/lock
  network: host
transport:
  name: dokken
provisioner:
  name: dokken
platforms:
  - name: ubuntu-14.04
    driver:
      image: dokken/ubuntu-14.04
      pid_one_command: /sbin/init
      ports: '8082'
    run_list:
      - recipe[apt]
suites:
  - name: server
    run_list:
      - recipe[cdo-pmm]
      - recipe[cdo-mysql::server]
      - recipe[cdo-pmm::client]
  - name: client
    run_list:
      - recipe[cdo-pmm::client]
